### PR TITLE
Reload button

### LINKED ISSUE #11: Refresh button
Hi there,

Great work - loving your captcha bot! I had one idea that would be great to implement. A `Refresh` button in case the captcha is really hard / barley readable.

Keep it up!

### PR DESCRIPTION
**Pull request by coder2020official**
Refresh button is added. Not sure merge it or not. I tested it, works well for me. It should be tested more.

### CODE REVIEW

**Comment by tinderboxmedia** [comment]
There is a random print statement on line 389:

https://github.com/coder2020official/pyTelegramBotCAPTCHA/blob/f933ca566a9c16d76b5e8011dcd9f7a9bebc94dc/pyTelegramBotCaptcha/telebot_captcha.py#L389

Also found a small typo on line 238 (lenghth -> length):

https://github.com/coder2020official/pyTelegramBotCAPTCHA/blob/f933ca566a9c16d76b5e8011dcd9f7a9bebc94dc/pyTelegramBotCaptcha/telebot_captcha.py#L238

---

The refresh button does what it's suppose to do. I'm wondering however if the max_reloads should be tied into previous_tries. Technically a refresh could be seen as a forfeit of an attempt (the same as trying to solve it but you can't and thus randomly try something which ends up being wrong). This is where the refresh button comes in, it will just allow you to skip the unreadable image faster, but it will use a try. Something to think about.

**Comment by coder2020official** [comment]
Oh, i had problems with timeout, left the random print.
If max reloads is tied to previous_tries, then it will be counted as an attempt, so i think it is not good to count refresh as an attempt.
I will correct typo and primt statement, and we will wait for @SwissCorePy :)

**Comment by SwissCorePy** [comment]
Looks good for me :) Thank You

**Comment by coder2020official** [comment]
Did u test?
There is a print statement left, and typo, should correct

**Review by SwissCorePy — APPROVED** [review]

**Pull request merged**
